### ISSUE TITLE
teleport limit

### ISSUE THREAD

**Issue by Marrarus** [JGSBroadcast/TeleportationTools#1]
hey i got a problem with the plugin: i set in the config the max tp range to 15.000 but when users use the comment ingame they get teleported more than 200.000 blocks away which make the server rly laggy.

**Comment by JGSBroadcast** [comment]
Are there any errors in the console and have you tried setting it to simply 15, not 15.000?

**Comment by Marrarus** [comment]
fixed with an reinstall. but ty for the quick answer :D
